package com.datarobort.ai.graph;

import lombok.Data;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.CopyOnWriteArrayList;

/**
 * Mutable state bag carried through every node in the graph.
 */
@Data
public class AgentState {

    // --- Input ---
    private String userQuestion;
    private Long agentId;
    private Long conversationId;   // bound conversation (multi-turn), nullable
    private Map<String, Object> agentConfig = new LinkedHashMap<>();

    // --- Intent ---
    private String intent;           // chat | query | analyze | report
    private double intentConfidence;

    // --- Knowledge recall ---
    private String recallContext;    // merged recall result as prompt text

    // --- SQL ---
    private String generatedSql;
    private String sqlError;         // validation error messages
    private int sqlRetryCount;

    // --- Query result ---
    private List<Map<String, Object>> queryResult;
    private long rowCount;
    private String resultSummary;    // LLM-generated summary of tabular data

    // --- Python ---
    private String pythonCode;
    private String pythonResult;     // JSON string from sandbox
    private String pythonError;

    // --- Chart ---
    private String chartOption;      // ECharts option JSON

    // --- Chart images (base64 PNG generated by the Python sandbox) ---
    private List<ChartImage> chartImages = new ArrayList<>();

    // --- Report ---
    private String markdownReport;
    private String reportFileUrl;    // URL of the generated HTML report file

    // --- Tracing ---
    private List<NodeTrace> traces = new CopyOnWriteArrayList<>();
    private Instant startedAt = Instant.now();

    // --- Error ---
    private boolean failed;
    private String errorMessage;

    @Data
    public static class NodeTrace {
        private String node;
        private String status;       // started | done | failed
        private long durationMs;
        private String message;
    }

    @Data
    public static class ChartImage {
        private String title;
        private String imageBase64;
    }

    public void addTrace(String node, String status, long durationMs, String message) {
        NodeTrace t = new NodeTrace();
        t.setNode(node); t.setStatus(status); t.setDurationMs(durationMs); t.setMessage(message);
        traces.add(t);
    }

    public boolean isIntent(String... intents) {
        if (intent == null) return false;
        for (String i : intents) {
            if (i.equals(intent)) return true;
        }
        return false;
    }
}
